site_name: POML Documentation
site_url: https://microsoft.github.io/poml
repo_url: https://github.com/microsoft/poml
repo_name: microsoft/poml
edit_uri: edit/main/docs/

exclude_docs: |
  typescript/reference/README.md

theme:
  name: material
  logo: media/logo-64-white.png
  favicon: media/logo-16-purple.png
  features:
    - navigation.sections
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tooltips
  palette:
    - scheme: default
      primary: poml
      accent: poml
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: poml
      accent: poml
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - stylesheets/extra.css

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-authors
  - mkdocstrings:
      handlers:
        python:
          paths: [python]
          options:
            show_source: true
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_style: google
            heading_level: 2

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

nav:
  - Getting Started: index.md
  - Tutorial:
    - Quick Start: tutorial/quickstart.md
  - Language Spec:
    - Write .poml Files: language/standalone.md
    - Meta: language/meta.md
    - Components: language/components.md
  - Visual Studio Code:
    - Overview: vscode/index.md
    - Features: vscode/features.md
    - Configuration: vscode/configuration.md
  - TypeScript:
    - Overview: typescript/index.md
    - Modules:
      - index: typescript/reference/index.md
      - base: typescript/reference/base.md
      - cli: typescript/reference/cli.md
      - essentials: typescript/reference/essentials.md
      - file: typescript/reference/file.md
      - writer: typescript/reference/writer.md
      - components: typescript/reference/components.md
  - Python:
    - Overview: python/index.md
    - References:
      - Core: python/reference/core.md
      - Integration: python/reference/integration.md
  - Deep Dive:
    - IR Specification: deep-dive/ir.md
    - Proposals:
      - Extended POML: deep-dive/proposals/poml_extended.md

extra:
  version:
    provider: mike
    default: latest