name: 'Integration Test Steps'
description: 'Shared steps for running integration tests'
inputs:
  integration:
    description: 'Integration type (agentops, mlflow, weave)'
    required: true
  agentops-api-key:
    description: 'AgentOps API Key'
    required: false
  openai-api-base:
    description: 'OpenAI API Base URL'
    required: true
  openai-api-key:
    description: 'OpenAI API Key'
    required: true
  wandb-api-key:
    description: 'W&B API Key'
    required: false

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'

    - name: Use Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install Node dependencies
      run: npm ci
      shell: bash

    - name: Build CLI
      run: npm run build-cli
      shell: bash

    - name: Install POML from source
      run: python -m pip install -e .[agent]
      shell: bash

    - name: Setup MLflow tracking server
      if: inputs.integration == 'mlflow'
      run: |
        mlflow server --host 127.0.0.1 --port 5000 &
        sleep 10  # Wait for server to start
      shell: bash

    - name: Run ${{ inputs.integration }} baseline test
      env:
        # Common environment variables
        OPENAI_API_BASE: ${{ inputs.openai-api-base }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        # AgentOps specific
        AGENTOPS_API_KEY: ${{ inputs.agentops-api-key }}
        # MLflow specific
        MLFLOW_TRACKING_URI: 'http://localhost:5000'
        # Weave specific (uses WANDB)
        WANDB_API_KEY: ${{ inputs.wandb-api-key }}
      run: |
        cd python/tests/integration
        python ${{ inputs.integration }}_baseline.py
      shell: bash

    - name: Run ${{ inputs.integration }} integration tests
      env:
        # Common environment variables
        OPENAI_API_BASE: ${{ inputs.openai-api-base }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        # AgentOps specific
        AGENTOPS_API_KEY: ${{ inputs.agentops-api-key }}
        # MLflow specific
        MLFLOW_TRACKING_URI: 'http://localhost:5000'
        # Weave specific (uses WANDB)
        WANDB_API_KEY: ${{ inputs.wandb-api-key }}
      run: |
        cd python/tests/integration
        python ${{ inputs.integration }}_poml.py
      shell: bash

    - name: Run mlflow additional integration tests
      if: inputs.integration == 'mlflow'
      env:
        OPENAI_API_BASE: ${{ inputs.openai-api-base }}
        OPENAI_API_KEY: ${{ inputs.openai-api-key }}
        MLFLOW_TRACKING_URI: 'http://localhost:5000'
      run: |
        cd python/tests/integration
        python mlflow_poml_langchain.py
      shell: bash
