name: VSCode Extension Package

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    - name: Use Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - run: npm ci
    - run: npm run build-webview
    - run: npm run build-cli
    - run: npm run package
    - run: python -m pip install -e .[dev]
    - run: hatch build -t wheel
    - uses: actions/upload-artifact@v4
      with:
        name: poml-vscode-${{ matrix.os }}
        path: "*.vsix"
    - uses: actions/upload-artifact@v4
      with:
        name: poml-python-${{ matrix.os }}
        path: dist/*
