name: Integration Tests

on:
  schedule:
    - cron: '0 0 * * *' # Run once daily at midnight UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        integration: [agentops, mlflow, weave]
      fail-fast: false

    steps:
      - name: Run integration tests
        uses: ./.github/actions/test-integration
        with:
          integration: ${{ matrix.integration }}
          agentops-api-key: ${{ secrets.AGENTOPS_API_KEY }}
          openai-api-base: ${{ secrets.OPENAI_API_BASE }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          wandb-api-key: ${{ secrets.WANDB_API_KEY }}

  test-cross-platform:
    runs-on: ${{ matrix.os }}
    needs: test-linux
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        integration: [agentops, mlflow, weave]
      fail-fast: false

    steps:
      - name: Run integration tests
        uses: ./.github/actions/test-integration
        with:
          integration: ${{ matrix.integration }}
          agentops-api-key: ${{ secrets.AGENTOPS_API_KEY }}
          openai-api-base: ${{ secrets.OPENAI_API_BASE }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          wandb-api-key: ${{ secrets.WANDB_API_KEY }}
